language: node_js
node_js:
- "stable"
install: 
# Install the dependencies
- npm install
services:
# Add the PostgreSQL dependency
- postgresql
env:
# Set the environment variable as 'test'
- export NODE_ENV=test
before_script:
# BACKEND
# Go to the backend folder
- cd backend
# Install dependencies for the backend
- npm install
# Create a DB
- psql -c 'create database gesture_web_test;' -U postgres
# Install the Sequelize CLI globally
- npm install sequelize-cli -g
# Install the Sequelize CLI locally 
- npm install --save sequelize
# Install the Sequelize CLI 
- npm install sequelize-cli
# Copy the config.json file for Travis to a new file with the proper extension
- cp server/config/config.json.travis server/config/config.json
######################################
# FRONTEND
# Go to the frontend folder
- cd ../frontend/
# Install the for the frontend
- npm install
script: 
# Go to the backend folder
- cd ../backend
# Execute backend test script.
- npm test
# Go to the frontend folder
- cd ../frontend/
# Execute the Angular frontend tests
- ng test 
