language: node_js
node_js:
- "stable"
install: 
# Install the dependencies
- npm install
services:
# Add the PostgreSQL dependency
- postgresql
custom:
  webpackIncludeModules:
    forceInclude:
    # Include the PostgreSQL client for Node.js.
      - pg
env:
# Set the environment variable as 'test'
- NODE_ENV=test
before_script:
# Install pg
- npm install pg --save
# Install pg hstore
- npm install pg-hstore --save
# Install Mocha
- npm install mocha --save
# Install Nodemon
- npm install nodemon --save
# Create a DB
- psql -c 'create database gesture_web_test;' -U postgres
# Go to the backend folder
- cd backend
# Install the Sequelize CLI globally
- npm install sequelize-cli -g
# Install the Sequelize CLI locally 
- npm install --save sequelize 
# Install the Sequelize CLI 
- npm install sequelize-cli
# Copy the example config.json file to a new file with the proper extension
- cp server/config/config.json.example server/config/config.json
# Start the web server
- "npm start &"
script: 
  # Run the tests. You're now in the 'backend' folder.
  - npm test